### ISSUE TITLE
empty form after submit

### ISSUE THREAD

**Issue by damusnet** [insin/react-auto-form#1]
What is the recommended way - if any - to empty the form after submit?

**Comment by insin** [comment]
I assume you're using [uncontrolled form components](http://facebook.github.io/react/docs/forms.html#uncontrolled-components) (`defaultValue`, `defaultSelected` etc.)?

Give it a `ref`:

``` js
<AutoForm ref="myForm" onSubmit={this.handleSubmit}>
  ...
```

Then use it to get a hold of the `<form>` DOM node and call [`reset()`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLFormElement/reset):

``` js
React.findDOMNode(this.refs.myForm).reset()
```

If you're using [controlled components](http://facebook.github.io/react/docs/forms.html#controlled-components), just set the state which provides their values back to whatever if was initially.

**Comment by damusnet** [comment]
Yes, precisely, I'm using uncontrolled form components and react-auto-form is really helpful in that situation. Calling `React.findDOMNode(this.refs.myForm).reset()` seems like a very nice solution, thank you :)

**Comment by insin** [comment]
The 80s Action option is to give the component a `key` and change the key value on submit so React blows the entire form away.
