### ISSUE TITLE
Unusable with React 16

### ISSUE THREAD

**Issue by alex996** [insin/react-auto-form#8]
**Description**

The package does not seem to work with React 16, specifically 16.2.0.

**Demo**

https://codesandbox.io/s/wom37977p8

**Reproduction**

I also installed the same setup locally, but got the same error: `TypeError: Cannot read property 'any' of undefined` in `./node_modules/react-auto-form/lib/index.js`.

Any plans to update to React 16?

**Comment by insin** [comment]
Fixed in v2.0.0.

`AutoForm` is also the `default` export, so the import would need to be `import AutoForm from 'react-auto-form'`

**Comment by alex996** [comment]
@insin Awesome, you're the man!
